name: get-jiku-ch-tmp
on:
  workflow_dispatch:
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: show encoded channel id
        env:
          CH: ${{ secrets.LW_JIKU_CH }}
        run: python3 -c "import base64,os; print(base64.b64encode(os.environ['CH'].encode()).decode())"
